### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by niansa** [travisbhartwell/pybasic#1]
Hi, I'd like to use this cool project in mine but I am not able to do so as this project is missing a license which makes it *all rights reserved to author*.
Could you add some open source license?

**Comment by travisbhartwell** [comment]
Thanks for your request. I had originally just thrown this code up here to share something simple I threw together. I have added an MIT license in commit dd8c766.

You are free to use this as meets the terms of the MIT license. I can't really offer any support because I wrote this code over 3 years ago and don't really remember much about it. :)

**Comment by niansa** [comment]
Thank you!
